import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Homepage from "./Homepage";
import { signIn, signOut, useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import {
  addDoc,
  collection,
  getDocs,
  query,
  serverTimestamp,
  where,
} from "firebase/firestore";
import { db2 } from "../Firebase";
// import Homepage from "./Homepage";

// PAGES

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession();
  const [isSessionSaved, setIsSessionSaved] = useState(false);

  const saveSession = async () => {
    if (session && !isSessionSaved) {
      const usersRef = collection(db2, "registered_Users");
      const q = query(usersRef, where("email", "==", session.user.email));
      const querySnapshot = await getDocs(q);

      if (querySnapshot.empty) {
        await addDoc(usersRef, {
          name: session.user.name,
          email: session.user.email,
          image: session.user.image,
          userId: session.user.uid,
          phone_number: "",
          department: "",
          startyear: "",
          endyear: "",
          time: serverTimestamp(),
        });
        console.log("User added to signedInUsers collection");
        setIsSessionSaved(true);
      } else {
        console.log("User already exists in signedInUsers collection");
        setIsSessionSaved(true);
      }
    }
  };
  useEffect(() => {
    saveSession();
  }, [session]);
  return (
    <section className="oo">
      <Head>
        <title>MAN ORON</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dk3iqiy2e/image/upload/v1685825962/WhatsApp_Image_2023-05-30_at_12.36.37_AM-removebg-preview_kxnfud.png"
        />
      </Head>
      <main className="app-main-con">
        {/* HOOME PAE */}
        {/* <button onClick={signIn}>out</button> */}
        <Homepage />
      </main>
    </section>
  );
}
